// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.1
// source: aggregation_service.proto

package aggregationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRoundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`                // e.g. "round-2026-03-15-0001"
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // e.g. "v1.4.1"
	Config        *RoundConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoundReq) Reset() {
	*x = StartRoundReq{}
	mi := &file_aggregation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoundReq) ProtoMessage() {}

func (x *StartRoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoundReq.ProtoReflect.Descriptor instead.
func (*StartRoundReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartRoundReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *StartRoundReq) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *StartRoundReq) GetConfig() *RoundConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RoundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalEpochs   int32                  `protobuf:"varint,1,opt,name=local_epochs,json=localEpochs,proto3" json:"local_epochs,omitempty"`         // local training epochs per client (default: 1)
	MinClients    int32                  `protobuf:"varint,2,opt,name=min_clients,json=minClients,proto3" json:"min_clients,omitempty"`            // minimum updates before aggregation proceeds
	DeadlineUnix  int64                  `protobuf:"varint,3,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`      // Unix timestamp — round closes at this time
	Dp            *DPConfig              `protobuf:"bytes,4,opt,name=dp,proto3" json:"dp,omitempty"`                                               // differential privacy parameters
	Compression   string                 `protobuf:"bytes,5,opt,name=compression,proto3" json:"compression,omitempty"`                             // "gzip" | "none" | "quantized_8bit"
	AsyncAllowed  bool                   `protobuf:"varint,6,opt,name=async_allowed,json=asyncAllowed,proto3" json:"async_allowed,omitempty"`      // if true, accept updates after deadline with penalty
	MiniBatchSize int32                  `protobuf:"varint,7,opt,name=mini_batch_size,json=miniBatchSize,proto3" json:"mini_batch_size,omitempty"` // mini-batch size for local training (default: 32)
	FedproxMu     float64                `protobuf:"fixed64,8,opt,name=fedprox_mu,json=fedproxMu,proto3" json:"fedprox_mu,omitempty"`              // FedProx regularisation strength (default: 0.01)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundConfig) Reset() {
	*x = RoundConfig{}
	mi := &file_aggregation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundConfig) ProtoMessage() {}

func (x *RoundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundConfig.ProtoReflect.Descriptor instead.
func (*RoundConfig) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{1}
}

func (x *RoundConfig) GetLocalEpochs() int32 {
	if x != nil {
		return x.LocalEpochs
	}
	return 0
}

func (x *RoundConfig) GetMinClients() int32 {
	if x != nil {
		return x.MinClients
	}
	return 0
}

func (x *RoundConfig) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *RoundConfig) GetDp() *DPConfig {
	if x != nil {
		return x.Dp
	}
	return nil
}

func (x *RoundConfig) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *RoundConfig) GetAsyncAllowed() bool {
	if x != nil {
		return x.AsyncAllowed
	}
	return false
}

func (x *RoundConfig) GetMiniBatchSize() int32 {
	if x != nil {
		return x.MiniBatchSize
	}
	return 0
}

func (x *RoundConfig) GetFedproxMu() float64 {
	if x != nil {
		return x.FedproxMu
	}
	return 0
}

type DPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epsilon       float64                `protobuf:"fixed64,1,opt,name=epsilon,proto3" json:"epsilon,omitempty"`                      // per-round DP epsilon target (default: 1.0)
	Delta         float64                `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`                          // DP delta (default: 1e-5)
	ClipNorm      float64                `protobuf:"fixed64,3,opt,name=clip_norm,json=clipNorm,proto3" json:"clip_norm,omitempty"`    // L2 gradient clip bound (default: 1.0)
	NoiseMult     float64                `protobuf:"fixed64,4,opt,name=noise_mult,json=noiseMult,proto3" json:"noise_mult,omitempty"` // Gaussian noise multiplier sigma (default: 1.1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DPConfig) Reset() {
	*x = DPConfig{}
	mi := &file_aggregation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPConfig) ProtoMessage() {}

func (x *DPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPConfig.ProtoReflect.Descriptor instead.
func (*DPConfig) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{2}
}

func (x *DPConfig) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *DPConfig) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *DPConfig) GetClipNorm() float64 {
	if x != nil {
		return x.ClipNorm
	}
	return 0
}

func (x *DPConfig) GetNoiseMult() float64 {
	if x != nil {
		return x.NoiseMult
	}
	return 0
}

type StartRoundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ModelUrl      string                 `protobuf:"bytes,2,opt,name=model_url,json=modelUrl,proto3" json:"model_url,omitempty"` // presigned MinIO GET URL for model_quant.onnx
	Deadline      int64                  `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`                // mirrors RoundConfig.deadline_unix for convenience
	RoundId       string                 `protobuf:"bytes,4,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`    // echo back so client can correlate async responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoundResp) Reset() {
	*x = StartRoundResp{}
	mi := &file_aggregation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoundResp) ProtoMessage() {}

func (x *StartRoundResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoundResp.ProtoReflect.Descriptor instead.
func (*StartRoundResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartRoundResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartRoundResp) GetModelUrl() string {
	if x != nil {
		return x.ModelUrl
	}
	return ""
}

func (x *StartRoundResp) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *StartRoundResp) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GetModelReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty string = "give me the current model".
	ModelVersion  string `protobuf:"bytes,1,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelReq) Reset() {
	*x = GetModelReq{}
	mi := &file_aggregation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelReq) ProtoMessage() {}

func (x *GetModelReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelReq.ProtoReflect.Descriptor instead.
func (*GetModelReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelReq) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type GetModelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelUrl      string                 `protobuf:"bytes,1,opt,name=model_url,json=modelUrl,proto3" json:"model_url,omitempty"`       // presigned MinIO GET URL (model_quant.onnx)
	ModelMeta     []byte                 `protobuf:"bytes,2,opt,name=model_meta,json=modelMeta,proto3" json:"model_meta,omitempty"`    // JSON-encoded model metadata blob (version, checksum, …)
	VocabUrl      string                 `protobuf:"bytes,3,opt,name=vocab_url,json=vocabUrl,proto3" json:"vocab_url,omitempty"`       // presigned URL for vocab_8192.model
	WeightsUrl    string                 `protobuf:"bytes,4,opt,name=weights_url,json=weightsUrl,proto3" json:"weights_url,omitempty"` // presigned URL for model_weights.pt (PyTorch checkpoint for training)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResp) Reset() {
	*x = GetModelResp{}
	mi := &file_aggregation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResp) ProtoMessage() {}

func (x *GetModelResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResp.ProtoReflect.Descriptor instead.
func (*GetModelResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelResp) GetModelUrl() string {
	if x != nil {
		return x.ModelUrl
	}
	return ""
}

func (x *GetModelResp) GetModelMeta() []byte {
	if x != nil {
		return x.ModelMeta
	}
	return nil
}

func (x *GetModelResp) GetVocabUrl() string {
	if x != nil {
		return x.VocabUrl
	}
	return ""
}

func (x *GetModelResp) GetWeightsUrl() string {
	if x != nil {
		return x.WeightsUrl
	}
	return ""
}

type SubmitUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UpdateBlob    []byte                 `protobuf:"bytes,3,opt,name=update_blob,json=updateBlob,proto3" json:"update_blob,omitempty"` // gzip( DP-applied float32 model delta )
	Meta          *UpdateMetadata        `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUpdateReq) Reset() {
	*x = SubmitUpdateReq{}
	mi := &file_aggregation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUpdateReq) ProtoMessage() {}

func (x *SubmitUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUpdateReq.ProtoReflect.Descriptor instead.
func (*SubmitUpdateReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitUpdateReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitUpdateReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubmitUpdateReq) GetUpdateBlob() []byte {
	if x != nil {
		return x.UpdateBlob
	}
	return nil
}

func (x *SubmitUpdateReq) GetMeta() *UpdateMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumSamples    int32                  `protobuf:"varint,1,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"` // local training sample count — used for FedAvg weight
	LocalEpochs   int32                  `protobuf:"varint,2,opt,name=local_epochs,json=localEpochs,proto3" json:"local_epochs,omitempty"`
	DpEpsilon     float64                `protobuf:"fixed64,3,opt,name=dp_epsilon,json=dpEpsilon,proto3" json:"dp_epsilon,omitempty"` // actual epsilon spent this round (from RDP accountant)
	DpDelta       float64                `protobuf:"fixed64,4,opt,name=dp_delta,json=dpDelta,proto3" json:"dp_delta,omitempty"`
	ClipNorm      float64                `protobuf:"fixed64,5,opt,name=clip_norm,json=clipNorm,proto3" json:"clip_norm,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // base model version this delta was computed from
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`                             // "sha256:<hex>" of update_blob
	DeviceClass   string                 `protobuf:"bytes,8,opt,name=device_class,json=deviceClass,proto3" json:"device_class,omitempty"`    // LAPTOP_SIM | ANDROID | ESP32 | OFFLOAD_WORKER
	IsStraggler   bool                   `protobuf:"varint,9,opt,name=is_straggler,json=isStraggler,proto3" json:"is_straggler,omitempty"`   // set server-side by Straggler Watch before aggregation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadata) Reset() {
	*x = UpdateMetadata{}
	mi := &file_aggregation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadata) ProtoMessage() {}

func (x *UpdateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadata.ProtoReflect.Descriptor instead.
func (*UpdateMetadata) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMetadata) GetNumSamples() int32 {
	if x != nil {
		return x.NumSamples
	}
	return 0
}

func (x *UpdateMetadata) GetLocalEpochs() int32 {
	if x != nil {
		return x.LocalEpochs
	}
	return 0
}

func (x *UpdateMetadata) GetDpEpsilon() float64 {
	if x != nil {
		return x.DpEpsilon
	}
	return 0
}

func (x *UpdateMetadata) GetDpDelta() float64 {
	if x != nil {
		return x.DpDelta
	}
	return 0
}

func (x *UpdateMetadata) GetClipNorm() float64 {
	if x != nil {
		return x.ClipNorm
	}
	return 0
}

func (x *UpdateMetadata) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *UpdateMetadata) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *UpdateMetadata) GetDeviceClass() string {
	if x != nil {
		return x.DeviceClass
	}
	return ""
}

func (x *UpdateMetadata) GetIsStraggler() bool {
	if x != nil {
		return x.IsStraggler
	}
	return false
}

type SubmitUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. "duplicate", "round_closed", "checksum_mismatch"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUpdateResp) Reset() {
	*x = SubmitUpdateResp{}
	mi := &file_aggregation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUpdateResp) ProtoMessage() {}

func (x *SubmitUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUpdateResp.ProtoReflect.Descriptor instead.
func (*SubmitUpdateResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitUpdateResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitUpdateResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MetricsReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RoundId             string                 `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	LocalTrainDurationS float64                `protobuf:"fixed64,3,opt,name=local_train_duration_s,json=localTrainDurationS,proto3" json:"local_train_duration_s,omitempty"`
	SamplesTrained      int32                  `protobuf:"varint,4,opt,name=samples_trained,json=samplesTrained,proto3" json:"samples_trained,omitempty"`
	DpEpsilonSpent      float64                `protobuf:"fixed64,5,opt,name=dp_epsilon_spent,json=dpEpsilonSpent,proto3" json:"dp_epsilon_spent,omitempty"`                // epsilon consumed in this round
	DpEpsilonCumulative float64                `protobuf:"fixed64,6,opt,name=dp_epsilon_cumulative,json=dpEpsilonCumulative,proto3" json:"dp_epsilon_cumulative,omitempty"` // total epsilon consumed by this client
	BatteryPercent      float64                `protobuf:"fixed64,7,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	Offloaded           bool                   `protobuf:"varint,8,opt,name=offloaded,proto3" json:"offloaded,omitempty"` // true if this client used the offload path
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricsReq) Reset() {
	*x = MetricsReq{}
	mi := &file_aggregation_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReq) ProtoMessage() {}

func (x *MetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReq.ProtoReflect.Descriptor instead.
func (*MetricsReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MetricsReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *MetricsReq) GetLocalTrainDurationS() float64 {
	if x != nil {
		return x.LocalTrainDurationS
	}
	return 0
}

func (x *MetricsReq) GetSamplesTrained() int32 {
	if x != nil {
		return x.SamplesTrained
	}
	return 0
}

func (x *MetricsReq) GetDpEpsilonSpent() float64 {
	if x != nil {
		return x.DpEpsilonSpent
	}
	return 0
}

func (x *MetricsReq) GetDpEpsilonCumulative() float64 {
	if x != nil {
		return x.DpEpsilonCumulative
	}
	return 0
}

func (x *MetricsReq) GetBatteryPercent() float64 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *MetricsReq) GetOffloaded() bool {
	if x != nil {
		return x.Offloaded
	}
	return false
}

type MetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResp) Reset() {
	*x = MetricsResp{}
	mi := &file_aggregation_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResp) ProtoMessage() {}

func (x *MetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResp.ProtoReflect.Descriptor instead.
func (*MetricsResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`          // client-provided hint; server may reassign
	DeviceClass   string                 `protobuf:"bytes,2,opt,name=device_class,json=deviceClass,proto3" json:"device_class,omitempty"` // LAPTOP_SIM | ANDROID | ESP32
	Caps          *DeviceCapabilities    `protobuf:"bytes,3,opt,name=caps,proto3" json:"caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_aggregation_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterReq) GetDeviceClass() string {
	if x != nil {
		return x.DeviceClass
	}
	return ""
}

func (x *RegisterReq) GetCaps() *DeviceCapabilities {
	if x != nil {
		return x.Caps
	}
	return nil
}

type DeviceCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RamMb         int32                  `protobuf:"varint,1,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	HasGpu        bool                   `protobuf:"varint,2,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	CpuCores      int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                            // "linux" | "android" | "freertos"
	CanTrain      bool                   `protobuf:"varint,5,opt,name=can_train,json=canTrain,proto3" json:"can_train,omitempty"`               // false for ESP32 — will always use offload path
	VocabSizeCap  int32                  `protobuf:"varint,6,opt,name=vocab_size_cap,json=vocabSizeCap,proto3" json:"vocab_size_cap,omitempty"` // max vocabulary size the device can load in memory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCapabilities) Reset() {
	*x = DeviceCapabilities{}
	mi := &file_aggregation_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities) ProtoMessage() {}

func (x *DeviceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeviceCapabilities) GetRamMb() int32 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *DeviceCapabilities) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *DeviceCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *DeviceCapabilities) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceCapabilities) GetCanTrain() bool {
	if x != nil {
		return x.CanTrain
	}
	return false
}

func (x *DeviceCapabilities) GetVocabSizeCap() int32 {
	if x != nil {
		return x.VocabSizeCap
	}
	return 0
}

type RegisterResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AssignedClientId string                 `protobuf:"bytes,2,opt,name=assigned_client_id,json=assignedClientId,proto3" json:"assigned_client_id,omitempty"` // canonical client_id to use in all subsequent calls
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_aggregation_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResp) GetAssignedClientId() string {
	if x != nil {
		return x.AssignedClientId
	}
	return ""
}

type InferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenIds      []int32                `protobuf:"varint,1,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"` // context window (up to 10 tokens)
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                    // number of suggestions to return (default: 3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferReq) Reset() {
	*x = InferReq{}
	mi := &file_aggregation_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferReq) ProtoMessage() {}

func (x *InferReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferReq.ProtoReflect.Descriptor instead.
func (*InferReq) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{14}
}

func (x *InferReq) GetTokenIds() []int32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *InferReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type InferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // decoded subword strings
	Scores        []float32              `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`  // raw logit values (not softmax)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResp) Reset() {
	*x = InferResp{}
	mi := &file_aggregation_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResp) ProtoMessage() {}

func (x *InferResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggregation_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResp.ProtoReflect.Descriptor instead.
func (*InferResp) Descriptor() ([]byte, []int) {
	return file_aggregation_service_proto_rawDescGZIP(), []int{15}
}

func (x *InferResp) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *InferResp) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_aggregation_service_proto protoreflect.FileDescriptor

const file_aggregation_service_proto_rawDesc = "" +
	"\n" +
	"\x19aggregation_service.proto\x12\x11fl.aggregation.v1\"\x87\x01\n" +
	"\rStartRoundReq\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.fl.aggregation.v1.RoundConfigR\x06config\"\xb1\x02\n" +
	"\vRoundConfig\x12!\n" +
	"\flocal_epochs\x18\x01 \x01(\x05R\vlocalEpochs\x12\x1f\n" +
	"\vmin_clients\x18\x02 \x01(\x05R\n" +
	"minClients\x12#\n" +
	"\rdeadline_unix\x18\x03 \x01(\x03R\fdeadlineUnix\x12+\n" +
	"\x02dp\x18\x04 \x01(\v2\x1b.fl.aggregation.v1.DPConfigR\x02dp\x12 \n" +
	"\vcompression\x18\x05 \x01(\tR\vcompression\x12#\n" +
	"\rasync_allowed\x18\x06 \x01(\bR\fasyncAllowed\x12&\n" +
	"\x0fmini_batch_size\x18\a \x01(\x05R\rminiBatchSize\x12\x1d\n" +
	"\n" +
	"fedprox_mu\x18\b \x01(\x01R\tfedproxMu\"v\n" +
	"\bDPConfig\x12\x18\n" +
	"\aepsilon\x18\x01 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x01R\x05delta\x12\x1b\n" +
	"\tclip_norm\x18\x03 \x01(\x01R\bclipNorm\x12\x1d\n" +
	"\n" +
	"noise_mult\x18\x04 \x01(\x01R\tnoiseMult\"t\n" +
	"\x0eStartRoundResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tmodel_url\x18\x02 \x01(\tR\bmodelUrl\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\x03R\bdeadline\x12\x19\n" +
	"\bround_id\x18\x04 \x01(\tR\aroundId\"2\n" +
	"\vGetModelReq\x12#\n" +
	"\rmodel_version\x18\x01 \x01(\tR\fmodelVersion\"\x88\x01\n" +
	"\fGetModelResp\x12\x1b\n" +
	"\tmodel_url\x18\x01 \x01(\tR\bmodelUrl\x12\x1d\n" +
	"\n" +
	"model_meta\x18\x02 \x01(\fR\tmodelMeta\x12\x1b\n" +
	"\tvocab_url\x18\x03 \x01(\tR\bvocabUrl\x12\x1f\n" +
	"\vweights_url\x18\x04 \x01(\tR\n" +
	"weightsUrl\"\xa1\x01\n" +
	"\x0fSubmitUpdateReq\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vupdate_blob\x18\x03 \x01(\fR\n" +
	"updateBlob\x125\n" +
	"\x04meta\x18\x04 \x01(\v2!.fl.aggregation.v1.UpdateMetadataR\x04meta\"\xb2\x02\n" +
	"\x0eUpdateMetadata\x12\x1f\n" +
	"\vnum_samples\x18\x01 \x01(\x05R\n" +
	"numSamples\x12!\n" +
	"\flocal_epochs\x18\x02 \x01(\x05R\vlocalEpochs\x12\x1d\n" +
	"\n" +
	"dp_epsilon\x18\x03 \x01(\x01R\tdpEpsilon\x12\x19\n" +
	"\bdp_delta\x18\x04 \x01(\x01R\adpDelta\x12\x1b\n" +
	"\tclip_norm\x18\x05 \x01(\x01R\bclipNorm\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12!\n" +
	"\fdevice_class\x18\b \x01(\tR\vdeviceClass\x12!\n" +
	"\fis_straggler\x18\t \x01(\bR\visStraggler\"F\n" +
	"\x10SubmitUpdateResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xc7\x02\n" +
	"\n" +
	"MetricsReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\tR\aroundId\x123\n" +
	"\x16local_train_duration_s\x18\x03 \x01(\x01R\x13localTrainDurationS\x12'\n" +
	"\x0fsamples_trained\x18\x04 \x01(\x05R\x0esamplesTrained\x12(\n" +
	"\x10dp_epsilon_spent\x18\x05 \x01(\x01R\x0edpEpsilonSpent\x122\n" +
	"\x15dp_epsilon_cumulative\x18\x06 \x01(\x01R\x13dpEpsilonCumulative\x12'\n" +
	"\x0fbattery_percent\x18\a \x01(\x01R\x0ebatteryPercent\x12\x1c\n" +
	"\toffloaded\x18\b \x01(\bR\toffloaded\"\x1d\n" +
	"\vMetricsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x88\x01\n" +
	"\vRegisterReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fdevice_class\x18\x02 \x01(\tR\vdeviceClass\x129\n" +
	"\x04caps\x18\x03 \x01(\v2%.fl.aggregation.v1.DeviceCapabilitiesR\x04caps\"\xb4\x01\n" +
	"\x12DeviceCapabilities\x12\x15\n" +
	"\x06ram_mb\x18\x01 \x01(\x05R\x05ramMb\x12\x17\n" +
	"\ahas_gpu\x18\x02 \x01(\bR\x06hasGpu\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x1b\n" +
	"\tcan_train\x18\x05 \x01(\bR\bcanTrain\x12$\n" +
	"\x0evocab_size_cap\x18\x06 \x01(\x05R\fvocabSizeCap\"L\n" +
	"\fRegisterResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12,\n" +
	"\x12assigned_client_id\x18\x02 \x01(\tR\x10assignedClientId\"<\n" +
	"\bInferReq\x12\x1b\n" +
	"\ttoken_ids\x18\x01 \x03(\x05R\btokenIds\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"E\n" +
	"\tInferResp\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x02R\x06scores2\xf8\x03\n" +
	"\x12AggregationService\x12Q\n" +
	"\n" +
	"StartRound\x12 .fl.aggregation.v1.StartRoundReq\x1a!.fl.aggregation.v1.StartRoundResp\x12Q\n" +
	"\x0eGetGlobalModel\x12\x1e.fl.aggregation.v1.GetModelReq\x1a\x1f.fl.aggregation.v1.GetModelResp\x12W\n" +
	"\fSubmitUpdate\x12\".fl.aggregation.v1.SubmitUpdateReq\x1a#.fl.aggregation.v1.SubmitUpdateResp\x12L\n" +
	"\vEmitMetrics\x12\x1d.fl.aggregation.v1.MetricsReq\x1a\x1e.fl.aggregation.v1.MetricsResp\x12Q\n" +
	"\x0eRegisterClient\x12\x1e.fl.aggregation.v1.RegisterReq\x1a\x1f.fl.aggregation.v1.RegisterResp\x12B\n" +
	"\x05Infer\x12\x1b.fl.aggregation.v1.InferReq\x1a\x1c.fl.aggregation.v1.InferRespB)Z'github.com/x9z0/fls/proto/aggregationv1b\x06proto3"

var (
	file_aggregation_service_proto_rawDescOnce sync.Once
	file_aggregation_service_proto_rawDescData []byte
)

func file_aggregation_service_proto_rawDescGZIP() []byte {
	file_aggregation_service_proto_rawDescOnce.Do(func() {
		file_aggregation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregation_service_proto_rawDesc), len(file_aggregation_service_proto_rawDesc)))
	})
	return file_aggregation_service_proto_rawDescData
}

var file_aggregation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_aggregation_service_proto_goTypes = []any{
	(*StartRoundReq)(nil),      // 0: fl.aggregation.v1.StartRoundReq
	(*RoundConfig)(nil),        // 1: fl.aggregation.v1.RoundConfig
	(*DPConfig)(nil),           // 2: fl.aggregation.v1.DPConfig
	(*StartRoundResp)(nil),     // 3: fl.aggregation.v1.StartRoundResp
	(*GetModelReq)(nil),        // 4: fl.aggregation.v1.GetModelReq
	(*GetModelResp)(nil),       // 5: fl.aggregation.v1.GetModelResp
	(*SubmitUpdateReq)(nil),    // 6: fl.aggregation.v1.SubmitUpdateReq
	(*UpdateMetadata)(nil),     // 7: fl.aggregation.v1.UpdateMetadata
	(*SubmitUpdateResp)(nil),   // 8: fl.aggregation.v1.SubmitUpdateResp
	(*MetricsReq)(nil),         // 9: fl.aggregation.v1.MetricsReq
	(*MetricsResp)(nil),        // 10: fl.aggregation.v1.MetricsResp
	(*RegisterReq)(nil),        // 11: fl.aggregation.v1.RegisterReq
	(*DeviceCapabilities)(nil), // 12: fl.aggregation.v1.DeviceCapabilities
	(*RegisterResp)(nil),       // 13: fl.aggregation.v1.RegisterResp
	(*InferReq)(nil),           // 14: fl.aggregation.v1.InferReq
	(*InferResp)(nil),          // 15: fl.aggregation.v1.InferResp
}
var file_aggregation_service_proto_depIdxs = []int32{
	1,  // 0: fl.aggregation.v1.StartRoundReq.config:type_name -> fl.aggregation.v1.RoundConfig
	2,  // 1: fl.aggregation.v1.RoundConfig.dp:type_name -> fl.aggregation.v1.DPConfig
	7,  // 2: fl.aggregation.v1.SubmitUpdateReq.meta:type_name -> fl.aggregation.v1.UpdateMetadata
	12, // 3: fl.aggregation.v1.RegisterReq.caps:type_name -> fl.aggregation.v1.DeviceCapabilities
	0,  // 4: fl.aggregation.v1.AggregationService.StartRound:input_type -> fl.aggregation.v1.StartRoundReq
	4,  // 5: fl.aggregation.v1.AggregationService.GetGlobalModel:input_type -> fl.aggregation.v1.GetModelReq
	6,  // 6: fl.aggregation.v1.AggregationService.SubmitUpdate:input_type -> fl.aggregation.v1.SubmitUpdateReq
	9,  // 7: fl.aggregation.v1.AggregationService.EmitMetrics:input_type -> fl.aggregation.v1.MetricsReq
	11, // 8: fl.aggregation.v1.AggregationService.RegisterClient:input_type -> fl.aggregation.v1.RegisterReq
	14, // 9: fl.aggregation.v1.AggregationService.Infer:input_type -> fl.aggregation.v1.InferReq
	3,  // 10: fl.aggregation.v1.AggregationService.StartRound:output_type -> fl.aggregation.v1.StartRoundResp
	5,  // 11: fl.aggregation.v1.AggregationService.GetGlobalModel:output_type -> fl.aggregation.v1.GetModelResp
	8,  // 12: fl.aggregation.v1.AggregationService.SubmitUpdate:output_type -> fl.aggregation.v1.SubmitUpdateResp
	10, // 13: fl.aggregation.v1.AggregationService.EmitMetrics:output_type -> fl.aggregation.v1.MetricsResp
	13, // 14: fl.aggregation.v1.AggregationService.RegisterClient:output_type -> fl.aggregation.v1.RegisterResp
	15, // 15: fl.aggregation.v1.AggregationService.Infer:output_type -> fl.aggregation.v1.InferResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_aggregation_service_proto_init() }
func file_aggregation_service_proto_init() {
	if File_aggregation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregation_service_proto_rawDesc), len(file_aggregation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregation_service_proto_goTypes,
		DependencyIndexes: file_aggregation_service_proto_depIdxs,
		MessageInfos:      file_aggregation_service_proto_msgTypes,
	}.Build()
	File_aggregation_service_proto = out.File
	file_aggregation_service_proto_goTypes = nil
	file_aggregation_service_proto_depIdxs = nil
}
