// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: aggregation_service.proto

package aggregationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregationService_StartRound_FullMethodName     = "/fl.aggregation.v1.AggregationService/StartRound"
	AggregationService_GetGlobalModel_FullMethodName = "/fl.aggregation.v1.AggregationService/GetGlobalModel"
	AggregationService_SubmitUpdate_FullMethodName   = "/fl.aggregation.v1.AggregationService/SubmitUpdate"
	AggregationService_EmitMetrics_FullMethodName    = "/fl.aggregation.v1.AggregationService/EmitMetrics"
	AggregationService_RegisterClient_FullMethodName = "/fl.aggregation.v1.AggregationService/RegisterClient"
	AggregationService_Infer_FullMethodName          = "/fl.aggregation.v1.AggregationService/Infer"
)

// AggregationServiceClient is the client API for AggregationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregationServiceClient interface {
	// Server-side: start a new FL round and return the model URL to clients.
	StartRound(ctx context.Context, in *StartRoundReq, opts ...grpc.CallOption) (*StartRoundResp, error)
	// Fetch the current (or a specific) global model metadata + presigned URL.
	GetGlobalModel(ctx context.Context, in *GetModelReq, opts ...grpc.CallOption) (*GetModelResp, error)
	// Client submits its DP-protected model delta after local training.
	SubmitUpdate(ctx context.Context, in *SubmitUpdateReq, opts ...grpc.CallOption) (*SubmitUpdateResp, error)
	// Client pushes per-round telemetry to the server-side Prometheus gateway.
	EmitMetrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error)
	// Client or offload worker registers with the system on first contact.
	RegisterClient(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	// Inference proxy: web keyboard calls this when local ONNX model is absent.
	Infer(ctx context.Context, in *InferReq, opts ...grpc.CallOption) (*InferResp, error)
}

type aggregationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregationServiceClient(cc grpc.ClientConnInterface) AggregationServiceClient {
	return &aggregationServiceClient{cc}
}

func (c *aggregationServiceClient) StartRound(ctx context.Context, in *StartRoundReq, opts ...grpc.CallOption) (*StartRoundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRoundResp)
	err := c.cc.Invoke(ctx, AggregationService_StartRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) GetGlobalModel(ctx context.Context, in *GetModelReq, opts ...grpc.CallOption) (*GetModelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResp)
	err := c.cc.Invoke(ctx, AggregationService_GetGlobalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) SubmitUpdate(ctx context.Context, in *SubmitUpdateReq, opts ...grpc.CallOption) (*SubmitUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitUpdateResp)
	err := c.cc.Invoke(ctx, AggregationService_SubmitUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) EmitMetrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResp)
	err := c.cc.Invoke(ctx, AggregationService_EmitMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) RegisterClient(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, AggregationService_RegisterClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) Infer(ctx context.Context, in *InferReq, opts ...grpc.CallOption) (*InferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferResp)
	err := c.cc.Invoke(ctx, AggregationService_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregationServiceServer is the server API for AggregationService service.
// All implementations must embed UnimplementedAggregationServiceServer
// for forward compatibility.
type AggregationServiceServer interface {
	// Server-side: start a new FL round and return the model URL to clients.
	StartRound(context.Context, *StartRoundReq) (*StartRoundResp, error)
	// Fetch the current (or a specific) global model metadata + presigned URL.
	GetGlobalModel(context.Context, *GetModelReq) (*GetModelResp, error)
	// Client submits its DP-protected model delta after local training.
	SubmitUpdate(context.Context, *SubmitUpdateReq) (*SubmitUpdateResp, error)
	// Client pushes per-round telemetry to the server-side Prometheus gateway.
	EmitMetrics(context.Context, *MetricsReq) (*MetricsResp, error)
	// Client or offload worker registers with the system on first contact.
	RegisterClient(context.Context, *RegisterReq) (*RegisterResp, error)
	// Inference proxy: web keyboard calls this when local ONNX model is absent.
	Infer(context.Context, *InferReq) (*InferResp, error)
	mustEmbedUnimplementedAggregationServiceServer()
}

// UnimplementedAggregationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregationServiceServer struct{}

func (UnimplementedAggregationServiceServer) StartRound(context.Context, *StartRoundReq) (*StartRoundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRound not implemented")
}
func (UnimplementedAggregationServiceServer) GetGlobalModel(context.Context, *GetModelReq) (*GetModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalModel not implemented")
}
func (UnimplementedAggregationServiceServer) SubmitUpdate(context.Context, *SubmitUpdateReq) (*SubmitUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitUpdate not implemented")
}
func (UnimplementedAggregationServiceServer) EmitMetrics(context.Context, *MetricsReq) (*MetricsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitMetrics not implemented")
}
func (UnimplementedAggregationServiceServer) RegisterClient(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedAggregationServiceServer) Infer(context.Context, *InferReq) (*InferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedAggregationServiceServer) mustEmbedUnimplementedAggregationServiceServer() {}
func (UnimplementedAggregationServiceServer) testEmbeddedByValue()                            {}

// UnsafeAggregationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregationServiceServer will
// result in compilation errors.
type UnsafeAggregationServiceServer interface {
	mustEmbedUnimplementedAggregationServiceServer()
}

func RegisterAggregationServiceServer(s grpc.ServiceRegistrar, srv AggregationServiceServer) {
	// If the following call pancis, it indicates UnimplementedAggregationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregationService_ServiceDesc, srv)
}

func _AggregationService_StartRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).StartRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_StartRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).StartRound(ctx, req.(*StartRoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_GetGlobalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).GetGlobalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_GetGlobalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).GetGlobalModel(ctx, req.(*GetModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_SubmitUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).SubmitUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_SubmitUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).SubmitUpdate(ctx, req.(*SubmitUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_EmitMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).EmitMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_EmitMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).EmitMetrics(ctx, req.(*MetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).RegisterClient(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).Infer(ctx, req.(*InferReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregationService_ServiceDesc is the grpc.ServiceDesc for AggregationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fl.aggregation.v1.AggregationService",
	HandlerType: (*AggregationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRound",
			Handler:    _AggregationService_StartRound_Handler,
		},
		{
			MethodName: "GetGlobalModel",
			Handler:    _AggregationService_GetGlobalModel_Handler,
		},
		{
			MethodName: "SubmitUpdate",
			Handler:    _AggregationService_SubmitUpdate_Handler,
		},
		{
			MethodName: "EmitMetrics",
			Handler:    _AggregationService_EmitMetrics_Handler,
		},
		{
			MethodName: "RegisterClient",
			Handler:    _AggregationService_RegisterClient_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _AggregationService_Infer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregation_service.proto",
}
