[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:offload-api]
command=/usr/local/bin/offload-api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="8085",REDIS_ADDR="%(ENV_REDIS_HOST)s:%(ENV_REDIS_PORT)s",MINIO_ENDPOINT="%(ENV_MINIO_ENDPOINT_RAW)s",MINIO_ACCESS_KEY="%(ENV_MINIO_ACCESS_KEY)s",MINIO_SECRET_KEY="%(ENV_MINIO_SECRET_KEY)s"

[program:offload-trainer]
command=python -m services.offload-worker.trainer.trainer
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
