# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aggregation_service_pb2 as aggregation__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aggregation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AggregationServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRound = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/StartRound',
                request_serializer=aggregation__service__pb2.StartRoundReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.StartRoundResp.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/GetGlobalModel',
                request_serializer=aggregation__service__pb2.GetModelReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.GetModelResp.FromString,
                _registered_method=True)
        self.SubmitUpdate = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/SubmitUpdate',
                request_serializer=aggregation__service__pb2.SubmitUpdateReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.SubmitUpdateResp.FromString,
                _registered_method=True)
        self.EmitMetrics = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/EmitMetrics',
                request_serializer=aggregation__service__pb2.MetricsReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.MetricsResp.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/RegisterClient',
                request_serializer=aggregation__service__pb2.RegisterReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.RegisterResp.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/fl.aggregation.v1.AggregationService/Infer',
                request_serializer=aggregation__service__pb2.InferReq.SerializeToString,
                response_deserializer=aggregation__service__pb2.InferResp.FromString,
                _registered_method=True)


class AggregationServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def StartRound(self, request, context):
        """Server-side: start a new FL round and return the model URL to clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Fetch the current (or a specific) global model metadata + presigned URL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitUpdate(self, request, context):
        """Client submits its DP-protected model delta after local training.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitMetrics(self, request, context):
        """Client pushes per-round telemetry to the server-side Prometheus gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Client or offload worker registers with the system on first contact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Inference proxy: web keyboard calls this when local ONNX model is absent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRound': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRound,
                    request_deserializer=aggregation__service__pb2.StartRoundReq.FromString,
                    response_serializer=aggregation__service__pb2.StartRoundResp.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=aggregation__service__pb2.GetModelReq.FromString,
                    response_serializer=aggregation__service__pb2.GetModelResp.SerializeToString,
            ),
            'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdate,
                    request_deserializer=aggregation__service__pb2.SubmitUpdateReq.FromString,
                    response_serializer=aggregation__service__pb2.SubmitUpdateResp.SerializeToString,
            ),
            'EmitMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitMetrics,
                    request_deserializer=aggregation__service__pb2.MetricsReq.FromString,
                    response_serializer=aggregation__service__pb2.MetricsResp.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=aggregation__service__pb2.RegisterReq.FromString,
                    response_serializer=aggregation__service__pb2.RegisterResp.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=aggregation__service__pb2.InferReq.FromString,
                    response_serializer=aggregation__service__pb2.InferResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl.aggregation.v1.AggregationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fl.aggregation.v1.AggregationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AggregationService(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def StartRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/StartRound',
            aggregation__service__pb2.StartRoundReq.SerializeToString,
            aggregation__service__pb2.StartRoundResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/GetGlobalModel',
            aggregation__service__pb2.GetModelReq.SerializeToString,
            aggregation__service__pb2.GetModelResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/SubmitUpdate',
            aggregation__service__pb2.SubmitUpdateReq.SerializeToString,
            aggregation__service__pb2.SubmitUpdateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/EmitMetrics',
            aggregation__service__pb2.MetricsReq.SerializeToString,
            aggregation__service__pb2.MetricsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/RegisterClient',
            aggregation__service__pb2.RegisterReq.SerializeToString,
            aggregation__service__pb2.RegisterResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.aggregation.v1.AggregationService/Infer',
            aggregation__service__pb2.InferReq.SerializeToString,
            aggregation__service__pb2.InferResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
